# Generated by Django 4.2.5 on 2023-10-04 08:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("badges", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserBagde",
            new_name="UserBadge",
        ),
    ]
