# Generated by Django 4.2.5 on 2023-10-04 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0003_model3d_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbadge",
            name="date_obtention",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
