# Generated by Django 4.2.5 on 2023-10-04 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0005_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
